export interface Product {
    id: number,
    name: string,
    price: number,
    compareAtPrice: number,
    images: string[],
    thumbimages: string[],
    badges: string[],
    rating: number,
    reviews: number,
    availability: string,
    seller: string,
    category: string,
    options: any[],
    features: any[],
    highlights: any[],
    description: any[],
    bankoffers: any[],
    ram: any[],
    storage: any[],
    epo: any[],
    replacement: any[],
    productdesc: any[],
    specifications: any[]
}